import threading
import time
from nos.req import http
from setup0 import *


#~ Tool I/O
def Laser(b, t_delay=0.25):
    if b:
        CheckRobotFlags()
        plc.write_coil(addr.laser_trigger, True)
        time.sleep(t_delay)
    else:
        robot.waitmove()
        plc.write_coil(addr.laser_trigger, False)



#~ System
def CheckRobotFlags(wait=True):
    if wait: robot.waitmove()
    status = robot.status(-1)[1]
    """
    status
        (0)  error code. 0=normal.
        (1)  in place flag. 0=not. 1=in place.
        (2)  powered flag. 0=off, 1=on.
        (3)  enabled flag. 0=off, 1=on.
        (4)  Rapidrate. Robots operation magnification
        (5)  Protective Stop. 0=no collision. 1=collision
        (6)  Drag State. 0=off, 1=on
        ...
        (22) socket connection. 0=dc, 1=connected
        (23) emergency stop. 0=not, 1=emergency stop
    """
    if not status[2]:
        raise Error(f'Raised ERROR: status[2]: {status[2]}')
    elif not status[3]:
        raise Error(f'Raised ERROR: status[3]: {status[3]}') # tripped when acceleration EM stop happens
    elif status[5]:
        raise Error(f'Raised ERROR: status[5]: {status[5]}')
    elif not status[22]:
        raise Error(f'Raised ERROR: status[22]: {status[22]}')
    elif status[23]:
        raise Error(f'Raised ERROR: status[23]: {status[23]}')



#~ Prog Ext
def prog_ext(p):
    """ Functions not generated by RoboDK """
    if p == 100: pass
    elif p == 0: plc.is_connection_active()
    else:
        print("!! program doesn't exist")
        return False
    return True






if __name__=="__main__":
    server.run_server()
    robot.init()
    robot.set_collision_val(1)



    robot.logout()
    server.stop_server()





